In [1]:
import pandas as pd
df = pd.read_csv(r"C:\\Users\hardy\diabetic_risk_project\diabetes_risk.csv")
print("sucess")

sucess

In [2]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                15000 non-null  int64
 1   age                       15000 non-null  int64
 2   gender                    15000 non-null  str
 3   city                      15000 non-null  str
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  str
 6   physical_activity_level   15000 non-null  str
 7   diet_type                 15000 non-null  str
 8   smoking_status            14528 non-null  str
 9   alcohol_consumption       11212 non-null  str
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64
 12  fasting_blood_sugar       15000 non-null  int64
 13  hba1c_level               15000 non-null  float64
 14  blood_pressure_systolic   15000 non-null  int64
 15  blood_pressure_diastolic  15000 non-null  int64
 16  waist_circumference_cm    15000 non-null  float64
 17  income_bracket            14537 non-null  str
 18  diabetes_risk             15000 non-null  str
dtypes: float64(4), int64(6), str(9)
memory usage: 2.9 MB

In [4]:
df.describe(include="all")

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
count,15000.000000,15000.000000,15000,15000,15000.000000,15000,15000,15000,14528,11212,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,14537,15000
unique,NaN,NaN,3,18,NaN,2,3,4,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3
top,NaN,NaN,Male,Mumbai,NaN,No,Active,Non-Vegetarian,Never,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Middle,Low
freq,NaN,NaN,7664,2243,NaN,9756,5100,8195,10119,5616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7305,9000
mean,7500.500000,44.333667,NaN,NaN,23.062260,NaN,NaN,NaN,NaN,NaN,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933,NaN,NaN
std,4330.271354,10.383753,NaN,NaN,4.046391,NaN,NaN,NaN,NaN,NaN,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331,NaN,NaN
min,1.000000,18.000000,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000,NaN,NaN
25%,3750.750000,38.000000,NaN,NaN,20.100000,NaN,NaN,NaN,NaN,NaN,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000,NaN,NaN
50%,7500.500000,45.000000,NaN,NaN,22.700000,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000,NaN,NaN
75%,11250.250000,52.000000,NaN,NaN,25.600000,NaN,NaN,NaN,NaN,NaN,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000,NaN,NaN
max,15000.000000,80.000000,NaN,NaN,40.800000,NaN,NaN,NaN,NaN,NaN,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000,NaN,NaN

In [5]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [6]:
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [7]:
df['smoking_status'] = df['smoking_status'].fillna(df.groupby('stress_level')['smoking_status'].transform(lambda x: x.mode()[0] if not x.mode().empty else 'never'))

In [8]:
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status                 0
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [9]:
df['alcohol_consumption'] = df['alcohol_consumption'].fillna('unrecorded')

In [10]:
df.isnull().sum()

patient_id                    0
age                           0
gender                        0
city                          0
bmi                           0
family_history_diabetes       0
physical_activity_level       0
diet_type                     0
smoking_status                0
alcohol_consumption           0
hours_sleep_per_night         0
stress_level                  0
fasting_blood_sugar           0
hba1c_level                   0
blood_pressure_systolic       0
blood_pressure_diastolic      0
waist_circumference_cm        0
income_bracket              463
diabetes_risk                 0
dtype: int64

In [11]:
df['income_bracket'] = df['income_bracket'].fillna(df.groupby('city')['income_bracket'].transform(lambda x: x.mode()[0] if not x.mode().empty else 'not_specified'))

In [12]:
df.isnull().sum()

patient_id                  0
age                         0
gender                      0
city                        0
bmi                         0
family_history_diabetes     0
physical_activity_level     0
diet_type                   0
smoking_status              0
alcohol_consumption         0
hours_sleep_per_night       0
stress_level                0
fasting_blood_sugar         0
hba1c_level                 0
blood_pressure_systolic     0
blood_pressure_diastolic    0
waist_circumference_cm      0
income_bracket              0
diabetes_risk               0
dtype: int64

In [13]:
df = df.apply(lambda x: x.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_') if x.dtype == "object" else x)

In [14]:
df.columns

Index(['patient_id', 'age', 'gender', 'city', 'bmi', 'family_history_diabetes',
       'physical_activity_level', 'diet_type', 'smoking_status',
       'alcohol_consumption', 'hours_sleep_per_night', 'stress_level',
       'fasting_blood_sugar', 'hba1c_level', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'waist_circumference_cm', 'income_bracket',
       'diabetes_risk'],
      dtype='str')

In [15]:
df = df.drop_duplicates(keep='first')

In [16]:
df = df.rename(columns={'hba1c_level': 'avg_blood_sugar'})

In [17]:
df[['age', 'bmi', 'avg_blood_sugar', 'fasting_blood_sugar','waist_circumference_cm']].agg(['min', 'max'])

     age   bmi  avg_blood_sugar  fasting_blood_sugar  waist_circumference_cm
min   18  15.0              4.8                   72                    73.2
max   80  40.8             13.4                  400                   148.2

In [18]:
print(f"Shape: {df.shape} | Total Nulls: {df.isnull().sum().sum()} | Data Consistency: Passed")

Shape: (15000, 19) | Total Nulls: 0 | Data Consistency: Passed

In [19]:
print(f"Is patient_id unique? {df['patient_id'].is_unique} | Duplicate IDs count: {df['patient_id'].duplicated().sum()}")

Is patient_id unique? True | Duplicate IDs count: 0

In [20]:
print({col: df[col].unique().tolist() for col in ['gender', 'city', 'diabetes_risk']})

{'gender': ['Female', 'Male', 'Other'], 'city': ['Mumbai', 'Thane', 'Bengaluru', 'Hyderabad', 'Delhi', 'Kolkata', 'Ahmedabad', 'Pune', 'Chennai', 'Kanpur', 'Bhopal', 'Visakhapatnam', 'Patna', 'Jaipur', 'Surat', 'Nagpur', 'Indore', 'Lucknow'], 'diabetes_risk': ['Low', 'High', 'Moderate']}

In [21]:
print(df[['bmi', 'fasting_blood_sugar', 'avg_blood_sugar', 'waist_circumference_cm']].agg(['min', 'max', 'mean']))

           bmi  fasting_blood_sugar  avg_blood_sugar  waist_circumference_cm
min   15.00000            72.000000         4.800000               73.200000
max   40.80000           400.000000        13.400000              148.200000
mean  23.06226           168.789933         6.878387              100.207933

In [22]:
df.to_csv(r"C:\Users\hardy\diabetic_risk_project\cleaned_patient_data.csv", index=False)

In [23]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

username = "use your username"
# Wrap the password in quote_plus to safely encode the '@' character
password = quote_plus("use your password")  
host = "localhost"
port = "5432"
database = "diabetic_risk_analysis"

# Create the engine using the encoded password
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "patient"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into the table '{table_name}' in database '{database}'.")

Data successfully loaded into the table 'patient' in database 'diabetic_risk_analysis'.